name: Continuous Persistent VPS

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:

jobs:
  vps-session:
    runs-on: ubuntu-latest
    timeout-minutes: 350  # Just under 6 hours

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set hostname
        run: sudo hostnamectl set-hostname miner-vps

      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt install -y curl unzip git build-essential cmake libssl-dev

   - name: Install dependencies
  run: |
    sudo apt update
    sudo apt install -y git build-essential cmake libuv1-dev libssl-dev libhwloc-dev

- name: Clone XMRig
  run: git clone https://github.com/xmrig/xmrig.git

- name: Build XMRig
  run: |
    cd xmrig
    mkdir build && cd build
    cmake ..
    make -j$(nproc)

      - name: Keep VPS alive
        run: sleep 21600  # 6 hours
